#!/bin/bash
#
# http://marxsoftware.blogspot.com.es/2013/08/searching-jars-for-string-linux.html
#

# echo "Searching JARs for class '${1}'"
# for i in `find . -iname "*.jar"`
# do
#   contents=`jar -tvf ${i} | grep ${1}`
#   if [ $? -eq 0 ]
#   then
#     echo "-----------  ${i} ----------------"
#     echo "${contents}"
#   fi
# done

printf "Searching JARs for class '${1}'...\n"
find . -iname "*.jar" -printf "jar -tvf %p | grep '${1}' && echo %p\n" | sh
